/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaDeLogin;


import com.mycompany.mavenproject1.Listas;
import javax.swing.JDesktopPane;


/**
 *
 * @author Gustavo Caramasqui
 */
public class TelaMenu extends javax.swing.JFrame {

    private TelaMenu TelaMenu;
    
     

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }
    private TelaMenu Menu;
    private TelaAtendente CadastroAtendente;
    private TelaProduto CadastroProduto;
    
    
     public JDesktopPane getDskPainelPrincipal() {
        return DskPainelPrincipal;
    }

    public void setDskPainelPrincipal(JDesktopPane dskPainelPrincipal) {
        this.DskPainelPrincipal = dskPainelPrincipal;
    }
    public void telaVenda(){
        //verifica se a tela ja existe
        if(Menu == null )
        {   
            //se não existir faz uma tela
            Menu = new TelaMenu();
            Menu.TelaMenu = this;
        }
        
        //verifico se a tela ja esta no painel
        if(!Menu.isVisible())
        {    
            //mostro a tela no painel principal caso nao esteja la
            DskPainelPrincipal.add(Menu);//ESTAAAAA DANDO ERRRRROOOOOOO VER COM PROFESSOR
            Menu.setVisible(true);
        }
        
        //coloco ela na frente de todas para todos os casos
        Menu.toFront();
        
        //redimensiona tela para tamanho do painel
        Menu.setMaximum(true);
        
      
    }
     public void cadastrarProduto(){
         //verifica se a tela ja existe
        if(CadastroProduto == null )
        {   
            //se não existir faz uma tela
            CadastroProduto = new TelaProduto();
        }
        
        
        
        //verifico se a tela ja esta no painel
        if(!CadastroProduto.isVisible())
        {    
            //mostro a tela no painel principal caso nao esteja la
            DskPainelPrincipal.add(CadastroProduto);//ESTAAAAA DANDO ERRRRROOOOOOO VER COM PROFESSOR
            CadastroProduto.setVisible(true);
        }
        
        //coloco ela na frente de todas para todos os casos
        CadastroProduto.toFront();
        
        //redimensiona tela para tamanho do painel
        CadastroProduto.setMaximum(true);
        
    }
     public void cadastrarAtendente(){
        //verifica se a tela ja existe
        if(CadastroAtendente == null )
        {   
            //se não existir faz uma tela
            CadastroAtendente = new TelaAtendente();
        }
        
        //coloca cabecario de acordo com a funcao cadasto/alteracao
        CadastroAtendente.setCabecario("Cadastro de Cliente");
        
        //verifico se a tela ja esta no painel
        if(!CadastroAtendente.isVisible())
        {    
            //mostro a tela no painel principal caso nao esteja la
            DskPainelPrincipal.add(CadastroAtendente);//ESTAAAAA DANDO ERRRRROOOOOOO VER COM PROFESSOR
            CadastroAtendente.setVisible(true);
        }
        
        //coloco ela na frente de todas para todos os casos
        CadastroAtendente.toFront();
        
        //redimensiona tela para tamanho do painel
        CadastroAtendente.setMaximum(true);
        
    }    
       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Lcp = new javax.swing.JLabel();
        Lpp = new javax.swing.JLabel();
        Lau = new javax.swing.JLabel();
        Lpu = new javax.swing.JLabel();
        Lrv = new javax.swing.JLabel();
        Bcp = new javax.swing.JButton();
        Bpp = new javax.swing.JButton();
        Bau = new javax.swing.JButton();
        Bpu = new javax.swing.JButton();
        Brv = new javax.swing.JButton();
        Ler = new javax.swing.JLabel();
        Ber = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        DskPainelPrincipal = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bcp.setText("Cadastrar Produtos");
        Bcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcpActionPerformed(evt);
            }
        });

        Bpp.setText("Pesquisar Produtos");
        Bpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BppActionPerformed(evt);
            }
        });

        Bau.setText("Adicionar Usuários");
        Bau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BauActionPerformed(evt);
            }
        });

        Bpu.setText("Pesquisar Usuários");
        Bpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpuActionPerformed(evt);
            }
        });

        Brv.setText("Relatar Venda");
        Brv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrvActionPerformed(evt);
            }
        });

        Ber.setText("Emitir Relatório");
        Ber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BerActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DskPainelPrincipalLayout = new javax.swing.GroupLayout(DskPainelPrincipal);
        DskPainelPrincipal.setLayout(DskPainelPrincipalLayout);
        DskPainelPrincipalLayout.setHorizontalGroup(
            DskPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );
        DskPainelPrincipalLayout.setVerticalGroup(
            DskPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ler, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Lrv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ber, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Brv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Lpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lpp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lcp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bcp)
                                    .addComponent(Bpp)
                                    .addComponent(Bau)))
                            .addComponent(Bpu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(DskPainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(Lcp))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(Bcp)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(Bpp))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(Lpp)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(Bau))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(Lau)
                                .addGap(40, 40, 40)
                                .addComponent(Lpu)))
                        .addGap(81, 81, 81)
                        .addComponent(Bpu)
                        .addGap(33, 33, 33)
                        .addComponent(Lrv)
                        .addGap(30, 30, 30)
                        .addComponent(Brv)
                        .addGap(22, 22, 22)
                        .addComponent(Ler)
                        .addGap(31, 31, 31)
                        .addComponent(Ber))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(541, 541, 541)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DskPainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcpActionPerformed
      TelaProduto tp = new TelaProduto();
 tp.setVisible(true);
 dispose(); 
    }//GEN-LAST:event_BcpActionPerformed

    private void BppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BppActionPerformed
        TelaPesquisaProduto tpp = new TelaPesquisaProduto();
 tpp.setVisible(true);
 dispose();
 

    }//GEN-LAST:event_BppActionPerformed

    private void BauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BauActionPerformed
         TelaAtendente ta = new TelaAtendente();
 ta.setVisible(true);
 dispose();
    }//GEN-LAST:event_BauActionPerformed

    private void BpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpuActionPerformed
        TelaPesquisaAtendente tpa = new TelaPesquisaAtendente();
 tpa.setVisible(true);
 dispose();
 
 Listas lista = new Listas();
 lista.getUsuarios();
 
    }//GEN-LAST:event_BpuActionPerformed

    private void BrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrvActionPerformed
        TelaRegisroDeVenda trv = new TelaRegisroDeVenda();
 trv.setVisible(true);
 dispose();
    }//GEN-LAST:event_BrvActionPerformed

    private void BerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BerActionPerformed
          TelaRelatório ter = new TelaRelatório();
 ter.setVisible(true);
 dispose();
    }//GEN-LAST:event_BerActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    
     private void LcpMouseClicked(java.awt.event.MouseEvent evt) {                                    
      TelaProduto tp = new TelaProduto();
 tp.setVisible(true);
 dispose(); 
    }                                   

    private void LppMouseClicked(java.awt.event.MouseEvent evt) {                                    
        TelaPesquisaProduto tpp = new TelaPesquisaProduto();
 tpp.setVisible(true);
 dispose();
    }                                   

    private void LauMouseClicked(java.awt.event.MouseEvent evt) {                                    
         TelaAtendente ta = new TelaAtendente();
 ta.setVisible(true);
 dispose();
    }                                   

    private void LpuMouseClicked(java.awt.event.MouseEvent evt) {                                    
        TelaPesquisaAtendente tpa = new TelaPesquisaAtendente();
 tpa.setVisible(true);
 dispose();
    }                                   

    private void LrvMouseClicked(java.awt.event.MouseEvent evt) {                                    
        TelaRegisroDeVenda trv = new TelaRegisroDeVenda();
 trv.setVisible(true);
 dispose();
    }                                   

    private void LerMouseClicked(java.awt.event.MouseEvent evt) {                                    
          TelaRelatório ter = new TelaRelatório();
 ter.setVisible(true);
 dispose();
    }                      
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bau;
    private javax.swing.JButton Bcp;
    private javax.swing.JButton Ber;
    private javax.swing.JButton Bpp;
    private javax.swing.JButton Bpu;
    private javax.swing.JButton Brv;
    private javax.swing.JDesktopPane DskPainelPrincipal;
    private javax.swing.JLabel Lau;
    private javax.swing.JLabel Lcp;
    private javax.swing.JLabel Ler;
    private javax.swing.JLabel Lpp;
    private javax.swing.JLabel Lpu;
    private javax.swing.JLabel Lrv;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void setMaximum(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
