/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaDeLogin;

import com.mycompany.mavenproject1.Atendente;
import com.mycompany.mavenproject1.Listas;
import com.mycompany.mavenproject1.Produto;
import static java.lang.Float.parseFloat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo Caramasqui
 */
public class TelaProduto extends javax.swing.JFrame {

    Listas lista = new Listas();
    
    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttoncadastrop = new javax.swing.JButton();
        txtnomep = new javax.swing.JTextField();
        txtidp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaproduto = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        txtquantidadep = new javax.swing.JFormattedTextField();
        txtcustop = new javax.swing.JFormattedTextField();
        txtvendap = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 38, 15);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel2.setText("Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 10, 14, 15);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel3.setText("Quantidade");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 78, 15);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel4.setText("Custo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 70, 39, 15);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel5.setText("Venda");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 70, 42, 15);

        buttoncadastrop.setBackground(new java.awt.Color(0, 153, 51));
        buttoncadastrop.setForeground(new java.awt.Color(255, 255, 255));
        buttoncadastrop.setText("Cadastrar");
        buttoncadastrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncadastropActionPerformed(evt);
            }
        });
        getContentPane().add(buttoncadastrop);
        buttoncadastrop.setBounds(310, 150, 90, 22);

        txtnomep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomepActionPerformed(evt);
            }
        });
        getContentPane().add(txtnomep);
        txtnomep.setBounds(10, 30, 230, 22);

        txtidp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpActionPerformed(evt);
            }
        });
        getContentPane().add(txtidp);
        txtidp.setBounds(260, 30, 210, 22);

        tabelaproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Quantidade", "Custo", "Venda"
            }
        ));
        jScrollPane2.setViewportView(tabelaproduto);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 190, 490, 170);

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(410, 150, 72, 22);
        getContentPane().add(txtquantidadep);
        txtquantidadep.setBounds(20, 100, 60, 22);
        getContentPane().add(txtcustop);
        txtcustop.setBounds(170, 100, 60, 22);
        getContentPane().add(txtvendap);
        txtvendap.setBounds(320, 100, 60, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomepActionPerformed

    private void txtidpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpActionPerformed

    private void buttoncadastropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncadastropActionPerformed
        if(txtidp == null || txtnomep == null || txtquantidadep == null || txtcustop == null || txtvendap == null){
        JOptionPane.showMessageDialog(null,"É necessário preencher todos os campos!");
        }
        else{
        
        DefaultTableModel dtmProdutos = (DefaultTableModel) tabelaproduto.getModel();
        Object[] dados = {txtidp.getText(),txtnomep.getText(),txtquantidadep.getText(),txtcustop.getText(),txtvendap.getText()};
        dtmProdutos.addRow(dados);
        }
        String id = txtidp.getText();
         String nome = txtnomep.getText();
         Integer quantidade = Integer.parseInt(txtquantidadep.getText());
         float custo = Float.parseFloat(txtcustop.getText().replaceAll(",", "."));
         float venda = Float.parseFloat(txtvendap.getText().replaceAll(",", "."));
         
    
        Produto p = new Produto(id,nome,quantidade,custo,venda);
        
        System.out.print(p.getQuantidade());
        
        lista.cadastroProduto(p);
        
        txtidp.setText("");
         txtnomep.setText("");
          txtquantidadep.setText("");
          txtcustop.setText("");
           txtvendap.setText("");
             
    }//GEN-LAST:event_buttoncadastropActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaMenu tm = new TelaMenu();
 tm.setVisible(true);
 dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncadastrop;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaproduto;
    private javax.swing.JFormattedTextField txtcustop;
    private javax.swing.JTextField txtidp;
    private javax.swing.JTextField txtnomep;
    private javax.swing.JFormattedTextField txtquantidadep;
    private javax.swing.JFormattedTextField txtvendap;
    // End of variables declaration//GEN-END:variables

    void setMaximum(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
